import {Brand,Icon,PageLink as Link} from '../components/TrendsUi';
export default function AboutPage(){return <main className="detailShell"><header className="detailHeader"><Link href="/" aria-label="Roblox Trends home"><Brand/></Link><Link href="/" className="backLink"><Icon name="back" size={15}/> Back to overview</Link></header><article className="methodContent"><p className="eyebrow">A LITTLE CONTEXT GOES A LONG WAY</p><h1>Understand the signals.</h1><p className="methodIntro">Roblox Trends is a research space for curious creators. We collect public player counts and game details, then help you follow the experiences and genres getting attention.</p>
<section className="panel methodCard"><h2>A snapshot, about every 30 minutes.</h2><p>GitHub Actions collects public Roblox statistics and publishes the dashboard. Counts describe the latest successful collection, rather than a live stream. Collection timing can vary.</p><p>We follow chart games, configured games, and a bounded sample of recommendations. The totals describe our tracked sample, which does not include every Roblox experience.</p></section>
<section className="panel methodCard"><h2>What the numbers mean</h2><ul><li><strong>Players:</strong> concurrent players reported by Roblox at collection time.</li><li><strong>Change:</strong> the percentage change between recorded player counts across the available history in your selected range. Each game shows how much history was measured.</li><li><strong>Rating:</strong> positive votes divided by total positive and negative votes.</li><li><strong>Genre lens:</strong> the median player count across tracked games in a genre. Genre change uses the existing momentum calculation, which smooths smaller counts.</li><li><strong>Badges:</strong> a sample of badge details and awards. Awards cannot be treated as unique players, retention, or revenue.</li></ul></section>
<section className="panel methodCard"><h2>Let the history grow.</h2><p>A new game starts with one observation. We show missing history explicitly, and label partial windows instead of pretending a few hours represent a full month. Longer ranges become useful as we collect more observations.</p><p>Line charts show recorded observations. Candles group those observations into intervals: open is the first count, close is the last, and high/low are the highest/lowest collected counts. A single observation makes a flat candle; empty intervals stay empty. Sampled highs and lows can miss changes between collections. Both mode overlays the observation line on candles. The latest interval may still be incomplete.</p></section>
<section className="panel methodCard"><h2>Breakouts: observed growth with context.</h2><p>The Breakouts tab lists up to five steady growers across 3, 6, or 24 hours, with genre filters and separate early, single-jump, and cooling signals. These are formula-based observations, not machine learning forecasts.</p><p>Audience size at the start sets the thresholds: under 1,000 players needs +100 and 30% growth, 1,000–10,000 needs +300 and 20%, 10,000–75,000 needs +1,000 and 10%, and 75,000+ needs +3,000 and 8%. The smallest games must also reach 200 players. Both growth thresholds must hold across at least three recent observations spanning at least 54 minutes.</p><p>We require a baseline within 20 minutes of the window’s start, at least 90% of the requested history, four valid observations, and a latest count within 45 minutes of collection. Gaps above 45 minutes (75 minutes for the 24-hour window) prevent qualification. A single jump making up at least 70% of net gain is flagged separately, as is a fall of more than 25% from the observed peak.</p><p>Ranking weights growth relative to its size threshold: 60% percentage growth and 40% player gain, each capped at three times its threshold. This score does not estimate the chance of success. Genre counts only describe qualifying games in our tracked sample, and may reflect how many games we follow in each genre. Updates, events, and daily traffic can cause growth.</p></section>
<section className="panel methodCard"><h2>Your watchlist stays with you.</h2><p>Star games to save a shortlist in this browser. No account is required. Your list is not synced to other devices and can be lost if you clear browser storage.</p></section>
<section className="panel methodCard"><h2>Useful context, growing over time.</h2><p>Images, badge details, and recommendations come from Roblox’s public APIs. Extra details refresh in limited batches and display their collection time. Recommendations are supplied by Roblox.</p><p>Current momentum scores use formulas. Machine learning forecasts are not available yet. Private creator analytics requires permission for the relevant experience.</p></section>
<footer className="dashboardFooter"><span>Built to help you explore, compare, and get inspired.</span><Link href="/">Back to research <Icon name="arrow" size={13}/></Link></footer></article></main>;}
