"use client";
import {useEffect,useState} from 'react';
import {GameIcon,Icon,PageLink as Link,Sparkline} from './TrendsUi';
import {gameHref,type Dataset,type Game} from '../lib/dashboardData';
import {compact,duration,number,percent} from '../lib/display';

const statusLabels={spike:'Single jump',early:'Early movement',cooling:'Cooling off'} as const;
const compare=(hours:number)=>(a:Game,b:Game)=>(b.breakouts?.[hours]?.score??0)-(a.breakouts?.[hours]?.score??0)||(b.breakouts?.[hours]?.growthPct??0)-(a.breakouts?.[hours]?.growthPct??0)||a.id.localeCompare(b.id);

export default function BreakoutsPanel({dataset,loading,watchlist,toggle,ready}:{dataset:Dataset;loading:boolean;watchlist:string[];toggle:(id:string)=>void;ready:boolean}){
  const [hours,setHours]=useState(6);
  const [genre,setGenre]=useState('all');
  const [clock,setClock]=useState(0);
  useEffect(()=>{function tick(){setClock(Date.now());}tick();const timer=window.setInterval(tick,60000);return()=>window.clearInterval(timer);},[]);
  const available=dataset.games.some(game=>game.breakouts?.[hours]);
  const genres=[...new Set(dataset.games.map(game=>game.genreL1?.trim()||'Unknown'))].sort();
  const all=dataset.games.filter(game=>game.breakouts?.[hours]?.status==='sustained').sort(compare(hours));
  const filtered=all.filter(game=>genre==='all'||(game.genreL1?.trim()||'Unknown')===genre);
  const top=filtered.slice(0,5);
  const assessed=dataset.games.filter(game=>['sustained','belowThreshold','spike','early','cooling','zeroBaseline'].includes(game.breakouts?.[hours]?.status??''));
  const other=dataset.games.filter(game=>['spike','early','cooling'].includes(game.breakouts?.[hours]?.status??'')&&(genre==='all'||(game.genreL1?.trim()||'Unknown')===genre)).sort(compare(hours)).slice(0,3);
  const genreGroups=genres.map(label=>({label,games:all.filter(game=>(game.genreL1?.trim()||'Unknown')===label),tracked:dataset.games.filter(game=>(game.genreL1?.trim()||'Unknown')===label).length}))
    .filter(group=>group.games.length).sort((a,b)=>b.games.length-a.games.length||a.label.localeCompare(b.label)).slice(0,5);
  const generatedMs=Date.parse(dataset.meta.generatedAt??'');
  const stale=clock>0&&Number.isFinite(generatedMs)&&clock-generatedMs>75*60000;

  return <section className="breakoutsSpace" aria-label="Breakout research">
    <div className="breakoutToolbar"><div className="segmented" aria-label="Breakout observation window">{[3,6,24].map(value=><button key={value} aria-pressed={hours===value} className={hours===value?'active':''} onClick={()=>setHours(value)}>{value}H</button>)}</div><label className="breakoutGenreFilter">Genre <select value={genre} aria-label="Filter breakouts by genre" onChange={event=>setGenre(event.target.value)}><option value="all">All genres</option>{genres.map(label=><option key={label}>{label}</option>)}</select></label><span className="quietLabel">OBSERVED GROWTH · NO FORECASTS</span></div>
    {stale?<p className="breakoutNotice" role="status"><Icon name="info" size={17}/> This collection is over 75 minutes old. Rankings describe that snapshot; refreshes will show the next successful collection.</p>:null}
    <div className="breakoutSummary"><div><strong>{available?number(all.length):'—'}</strong><span>steady growers</span></div><div><strong>{available?number(assessed.length):'—'}<small> / {dataset.games.length}</small></strong><span>games with usable {hours}H history</span></div><div><strong>{available?number(dataset.games.length-assessed.length):'—'}</strong><span>need fuller or fresher history</span></div></div>
    <div className="breakoutLayout"><div className="breakoutMain"><div className="sectionHeading"><div><p className="eyebrow">SMALL GAMES. BIG POSSIBILITIES.</p><h2>Top five {genre==='all'?'steady growers':`in ${genre}`}</h2></div><span className="resultCount">{top.length} / 5</span></div><p className="sectionDescription">Ranked by growth relative to game size over {hours} hours. Gains must hold across at least three checks spanning at least 54 minutes.</p>
      <div className="breakoutCards">{top.map((game,index)=>{const signal=game.breakouts![hours];return <article className="panel breakoutCard" key={game.id}>
        <div className="breakoutCardHead"><span className="breakoutRank">{String(index+1).padStart(2,'0')}</span><Link className="breakoutIdentity" href={gameHref(game.id)}><GameIcon game={game}/><span><strong>{game.name}</strong><small>{game.creator}</small></span></Link><button className={`iconButton watchButton ${watchlist.includes(game.id)?'saved':''}`} aria-label={`${watchlist.includes(game.id)?'Remove':'Add'} ${game.name} ${watchlist.includes(game.id)?'from':'to'} watchlist`} aria-pressed={watchlist.includes(game.id)} disabled={!ready} onClick={()=>toggle(game.id)}><Icon name="watch" size={18}/></button></div>
        <div className="breakoutTags"><span className="genreTag">{game.genreL1?.trim()||'Unknown'}{game.genreL2?` / ${game.genreL2}`:''}</span><span>{signal.tier} audience</span><span className="breakoutHeld"><span className="statusDot"/> Held growth</span></div>
        <div className="breakoutNumbers"><div><strong className="positive">{percent(signal.growthPct)}</strong><small>across {duration(signal.hoursUsed)}</small></div><div><strong>+{number(signal.gain)}</strong><small>players gained</small></div><div><strong>{compact(game.activePlayers)}</strong><small>players at collection</small></div><div className="breakoutSpark"><Sparkline points={signal.sparkline}/><small>Recorded counts</small></div></div>
        <div className="breakoutCardFoot"><span>{signal.observations} observations · Largest gap {Math.round(signal.maxGapMinutes)} min</span><Link className="subtleLink" href={gameHref(game.id)}>Explore game <Icon name="arrow" size={14}/></Link></div>
      </article>;})}</div>
      {!top.length?<div className="panel breakoutEmpty"><Icon name="chart" size={32}/><h3>{loading?'Checking the latest snapshot…':!available?'Breakout signals are waiting for a new collection.':'No steady growers meet these criteria.'}</h3><p>{!available?'The collector will calculate these signals when it next publishes data.':genre!=='all'?'Try another genre or time window. We only list games that pass the history and growth checks.':'Try a different time window. Spikes and early moves stay separate while we collect more observations.'}</p></div>:top.length<5?<p className="chartNote">Only {filtered.length} {filtered.length===1?'game qualifies':'games qualify'} for this selection. We don’t fill the remaining spots with weaker signals.</p>:null}
      {other.length?<section className="breakoutDeveloping"><div className="sectionHeading"><h2>Movement to keep an eye on</h2><span className="quietLabel">OUTSIDE THE TOP FIVE</span></div><p className="sectionDescription">A single jump, gains that haven’t held long enough, or a fall from the recent peak.</p>{other.map(game=>{const signal=game.breakouts![hours];const label=statusLabels[signal.status as keyof typeof statusLabels];return <Link className="panel developingRow" key={game.id} href={gameHref(game.id)}><GameIcon game={game} size="small"/><span className="developingName"><strong>{game.name}</strong><small>{game.genreL1||'Unknown'} · {signal.tier}</small></span><span className="developingStatus">{label}<small className="positive">{percent(signal.growthPct)} across {duration(signal.hoursUsed)}</small></span><Icon name="arrow" size={15}/></Link>;})}</section>:null}
    </div><aside className="breakoutAside"><section className="panel breakoutGenres"><p className="eyebrow">WHERE THE GROWTH IS</p><h2>Genres on the move</h2><p className="sectionDescription">Steady growers in our tracked sample. Counts reflect our coverage of each genre.</p>{genreGroups.length?genreGroups.map(group=><button className={`breakoutGenreRow ${genre===group.label?'selected':''}`} key={group.label} onClick={()=>setGenre(genre===group.label?'all':group.label)} aria-pressed={genre===group.label}><span><strong>{group.label}</strong><small>{group.games.length} steady {group.games.length===1?'grower':'growers'} / {group.tracked} tracked</small><span className="genreGrowthBar"><i style={{width:`${group.games.length/group.tracked*100}%`}}/></span></span><Icon name="arrow" size={15}/></button>):<p className="chartNote">Genre leaders appear when games meet the steady-growth criteria.</p>}</section>
      <section className="panel breakoutMethod"><Icon name="info" size={20}/><h2>Why these five?</h2><p>Smaller audiences can qualify with smaller gains. Games must pass both the percentage and player-gain thresholds.</p><details><summary>See the growth rules</summary><table><caption>Audience size at the start of the window</caption><thead><tr><th>Players</th><th>Gain</th><th>Growth</th></tr></thead><tbody><tr><td>Under 1K</td><td>+100</td><td>30%</td></tr><tr><td>1K–10K</td><td>+300</td><td>20%</td></tr><tr><td>10K–75K</td><td>+1K</td><td>10%</td></tr><tr><td>75K+</td><td>+3K</td><td>8%</td></tr></tbody></table><p>Under-1K games must also reach 200 players. The top five require at least 90% of the selected history, a latest count within 45 minutes of collection, and no gaps above {hours===24?'75':'45'} minutes.</p><p>A jump accounting for 70% or more of the net gain is flagged separately. A drop of more than 25% from the window’s peak is “Cooling off.”</p><p>We rank steady growers by 60% relative percentage growth and 40% relative player gain, each capped at three times its threshold. This score is a sorting rule, not a probability.</p></details><p className="breakoutCaveat">Growth can reflect updates, events, or daily traffic patterns. This doesn’t predict future success.</p><Link className="subtleLink" href="/about">Understand the signals <Icon name="arrow" size={14}/></Link></section>
    </aside></div>
  </section>;
}
